name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '23 */1 * * *'

permissions:
  contents: write

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: |
        python3 update.py
    - name: Reset and commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "github-actions"
        git checkout --orphan latest_branch
        git add .
        git commit --allow-empty-message --no-edit
        git branch -D main
        git branch -m main
        git push --force origin main
